#!/bin/bash

# Navigate to the app directory
cd ~/app/

# Start the application
npm start

# Add all changes to git
git add .

# Commit the changes
git commit -m "Automated commit"

# Push the changes to the master branch
git push origin master
